CREATE TABLE infy_schema.USER
(
    USER_ID         int(20) NOT NULL AUTO_INCREMENT,
    USER_NAME       varchar (200) NOT NULL,
    PASSWORD        varchar (1000) NOT NULL,
    FIRST_NAME      varchar (100) NOT NULL,
    LAST_NAME       varchar (100) NOT NULL,
    EMAIL           varchar(200) NOT NULL,
    ACTIVE          tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY         varchar (255) DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_BY    varchar(255)   DEFAULT NULL,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY USER_UK (USER_NAME, FIRST_NAME, LAST_NAME, EMAIL),
    KEY USER_NAME_IDX (USER_NAME)
);

CREATE TABLE infy_schema.CLIENT
(
    CLIENT_ID       int(20) NOT NULL AUTO_INCREMENT,
    CLIENT_NAME     varchar (100) NOT NULL,
    TYPE            varchar (100) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (CLIENT_ID)

);

CREATE TABLE infy_schema.USER_SESSION
(
    USER_SESSION_ID     int(20)     NOT NULL AUTO_INCREMENT,
    USER_ID             int(20)     NOT NULL,
    CLIENT_ID           int(20)     NOT NULL,
    TOKEN               varchar(1000) DEFAULT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    LAST_LOGIN_TIMESTAMP   varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_ACCESS_TIMESTAMP   varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (USER_SESSION_ID),
    CONSTRAINT UST_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT UST_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES infy_schema.USER(USER_ID) ON DELETE NO ACTION on UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE
(
    TEMPLATE_ID     int(20)     NOT NULL AUTO_INCREMENT,
    CLIENT_ID       int(20)     NOT NULL,
    TEMPLATE_NAME   varchar(100) NOT NULL,
    TEMPLATE_OUTPUT_LOCATION       varchar(100) NOT NULL,
    TEMPLATE_SCHEMA_LOCATION       varchar(100) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_ID,CLIENT_ID),
    CONSTRAINT UST_TEMP_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE_MAPPING
(
    TEMPLATE_MAPPING_ID   int(20)     NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID           int(20)       NOT NULL,
    MAPPING_DATA        varchar(2000) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_MAPPING_ID,TEMPLATE_ID),
    CONSTRAINT UST_TEMPLATE_ID_FK FOREIGN KEY(TEMPLATE_ID) REFERENCES infy_schema.TEMPLATE (TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE_EXECUTION_DETAIL
(
    TEMPLATE_EXECUTION_DETAIL_ID   int(20)     NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID           int(20)       NOT NULL,
    CLIENT_ID  int(20)       NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_EXECUTION_DETAIL_ID,TEMPLATE_ID, CLIENT_ID),
    CONSTRAINT UST_TEMPLATE_DTL_ID1_FK FOREIGN KEY(TEMPLATE_ID) REFERENCES infy_schema.TEMPLATE (TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT UST_TEMP_DTL_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

COMMIT;