

CREATE TABLE infy_schema.USER
(
    USER_ID         int(20) NOT NULL AUTO_INCREMENT,
    USER_NAME       varchar (200) NOT NULL,
    PASSWORD        varchar (1000) NOT NULL,
    FIRST_NAME      varchar (100) NOT NULL,
    LAST_NAME       varchar (100) NOT NULL,
    EMAIL           varchar(200) NOT NULL,
    ACTIVE          tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY         varchar (255) DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_BY    varchar(255)   DEFAULT NULL,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY USER_UK (USER_NAME, FIRST_NAME, LAST_NAME, EMAIL),
    KEY USER_NAME_IDX (USER_NAME)
);



CREATE TABLE infy_schema.CLIENT
(
    CLIENT_ID       int(20) NOT NULL AUTO_INCREMENT,
    CLIENT_NAME     varchar (100) NOT NULL,
    TYPE            varchar (100) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (CLIENT_ID)

);

CREATE TABLE infy_schema.USER_SESSION
(
    USER_SESSION_ID     int(20)     NOT NULL AUTO_INCREMENT,
    USER_ID             int(20)     NOT NULL,
    CLIENT_ID           int(20)     NOT NULL,
    TOKEN               varchar(1000) DEFAULT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    LAST_LOGIN_TIMESTAMP   varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_ACCESS_TIMESTAMP   varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (USER_SESSION_ID),
    CONSTRAINT UST_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT UST_USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES infy_schema.USER(USER_ID) ON DELETE NO ACTION on UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE
(
    TEMPLATE_ID     int(20)     NOT NULL AUTO_INCREMENT,
    CLIENT_ID       int(20)     NOT NULL,
    TEMPLATE_NAME   varchar(100) NOT NULL,
    TEMPLATE_OUTPUT_LOCATION       varchar(100) NOT NULL,
    TEMPLATE_SCHEMA_LOCATION       varchar(100) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_ID,CLIENT_ID),
    CONSTRAINT UST_TEMP_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE_MAPPING
(
    TEMPLATE_MAPPING_ID   int(20)     NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID           int(20)       NOT NULL,
    MAPPING_DATA        varchar(2000) NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_MAPPING_ID,TEMPLATE_ID),
    CONSTRAINT UST_TEMPLATE_ID_FK FOREIGN KEY(TEMPLATE_ID) REFERENCES infy_schema.TEMPLATE (TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE infy_schema.TEMPLATE_EXECUTION_DETAIL
(
    TEMPLATE_EXECUTION_DETAIL_ID   int(20)     NOT NULL AUTO_INCREMENT,
    TEMPLATE_ID           int(20)       NOT NULL,
    CLIENT_ID  int(20)       NOT NULL,
    ACTIVE   tinyint(1)  NOT NULL DEFAULT '1',
    CRTD_BY     varchar (255) DEFAULT NULL,
    LAST_MDFD_BY            varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50) NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (TEMPLATE_EXECUTION_DETAIL_ID,TEMPLATE_ID, CLIENT_ID),
    CONSTRAINT UST_TEMPLATE_DTL_ID1_FK FOREIGN KEY(TEMPLATE_ID) REFERENCES infy_schema.TEMPLATE (TEMPLATE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT UST_TEMP_DTL_CLIENT_ID_FK FOREIGN KEY(CLIENT_ID) REFERENCES infy_schema.CLIENT (CLIENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

create table infy_schema.TEMPLATE_CLASS
(
	TEMPLATE_CLASS_ID int auto_increment,
	TEMPLATE_ID int not null,
	CLIENT_ID int not null,
	CLAZZ_NAME varchar(25) not null,
	SUPER_CLAZZ varchar(100) null,
	PACKAGE_NAME varchar(100) null,
	CLAZZ_OUTPUT_LOCATION varchar(100) not null,
	METHOD_URIS varchar(5000) not null,
	DESCRIPTION varchar(1000) null,
	ACTIVE tinyint(1) default 1 not null,
	CRTD_BY varchar(255) null,
	LAST_MDFD_BY varchar(255) null,
	CRTD_TS varchar(50) default '00-00-0000 00:00:00' not null,
	LAST_MDFD_TS varchar(50) default '00-00-0000 00:00:00' not null,
	primary key (TEMPLATE_CLASS_ID, TEMPLATE_ID, CLIENT_ID),
	constraint UST_TEMPLATE_DTL_ID3_FK
		foreign key (CLIENT_ID) references CLIENT (CLIENT_ID),
	constraint UST_TEMPLATE_ID3_FK
		foreign key (TEMPLATE_ID) references TEMPLATE (TEMPLATE_ID)
);

CREATE TABLE infy_schema.MT202
(
    MT202_ID        int(20)         NOT NULL AUTO_INCREMENT,
    TAG             varchar(100)    NOT NULL,
    FIELD_NAME      varchar(100)    NOT NULL,
    STATUS          varchar(100)    NOT NULL,
    ACTIVE          tinyint(1)      NOT NULL DEFAULT '1',
    CRTD_BY         varchar (255)   DEFAULT NULL,
    LAST_MDFD_BY    varchar(255)    DEFAULT NULL,
    CRTD_TS         varchar(50)     NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    LAST_MDFD_TS    varchar(50)     NOT NULL DEFAULT '00-00-0000 00:00:00' ,
    PRIMARY KEY (MT202_ID)
);


COMMIT;


