USE infy_schema;
DROP TABLE IF EXISTS infy_schema.USER_SESSION;
DROP TABLE IF EXISTS infy_schema.TEMPLATE_MAPPING;
DROP TABLE IF EXISTS infy_schema.TEMPLATE_EXECUTION_DETAIL;
DROP TABLE IF EXISTS infy_schema.USER;
DROP TABLE IF EXISTS infy_schema.TEMPLATE;
DROP TABLE IF EXISTS infy_schema.CLIENT;

COMMIT ;